### ISSUE TITLE
Desktop icon does not work

### ISSUE THREAD

**Issue by ghost** [darealshinji/UnityEngine2deb#1]
The shortcut placed in "/usr/share/applications" runs the shortcut placed in "/usr/games"; however, on Linux Mint, this shortcut attempts to launch the Unity game from the user's home directory and fails because it cannot find the "data" folder in that directory. I patched this in my own copy of u2deb by changing the default command of the shortcut in "/usr/share/applications" from "[game-name]" to "/usr/games/[game-name]". This ensures that the game begins running from the correct directory and can locate the "data" folder.

I changed line 383 in the u2deb script from:
`Exec=$name`
to:
`Exec=/usr/games/$name`

**Comment by darealshinji** [comment]
Thanks for your interest in UnityEngine2deb. I've changed the line as you suggested and hope it's now working.
