### ISSUE TITLE
After u2deb build - Cannot access '*.deb': No file or directory.

### ISSUE THREAD

**Issue by chaosmasterro** [darealshinji/UnityEngine2deb#5]
This is the error that I am receiving after I prepare my file and I prompted to build my game. The game is already exported as a .x86 file so I am just running the u2deb prepare and u2deb build. Any reason what is causing this error? Thanks.
-----

debian/make-icons.sh: 89: debian/make-icons.sh: identify: not found
debian/rules:47: recipe for target 'override_dh_auto_install' failed
make[1]: *** [override_dh_auto_install] Error 127
make[1]: Leaving directory '/tmp/UnityEngine2deb_tmpJP9jfsjwoj/build/x86'
debian/rules:43: recipe for target 'binary' failed
make: *** [binary] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2

ls: cannot access '*.deb': No such file or directory.

------

**Comment by darealshinji** [comment]
> debian/make-icons.sh: 89: debian/make-icons.sh: identify: not found

It can't find the `identify` command and aborts the build. That command is part of the `imagemagick` package which you should install first. The file `README.md` lists all dependencies that might be required.

Please let me know if installing `imagemagick` fixes this for you.

**Comment by chaosmasterro** [comment]
That cleaned up my first problem. I assumed the minimum and recommended dependencies were only for 'u2mojo'. Thank you.

However, during the u2deb build another issue occur.
-----------------------------  
strip:debian/test/usr/lib/games/test/test_Data/Plugins/x86_64/ScreenSelector.so: File format not recognized
dh_strip: strip --remove-section=.comment --remove-section=.note --strip-unneeded debian/test/usr/lib/games/test/test_Data/Plugins/x86_64/ScreenSelector.so returned exit code 1
debian/rules:43: recipe for target 'binary' failed
make: *** [binary] Error 29
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2

ls: cannot access '*.deb': No such file or directory

------------------------------

I made sure to add all of the minimum and required dependencies. Unless I over looked something. Thank you for the quick reply with the previous issue.

**Comment by darealshinji** [comment]
Don't add x86_64 plugins if you only have a x86 game.

**Comment by chaosmasterro** [comment]
I'm using the downloaded file "unity5.5.0-linux.tar.xz" that was provided in the instructions. A test.x86_64 and a test.x86 was provided. The home folder is named linux so that I run <u2deb prepare ./linux> and later run <u2deb build>. The process is automated to attempt to convert both, however I still see the same error. I remove the .x86 version from the directory and keep .x86_64 and vice-versa and still come across the errors. 
If it is any help I am also using a raspberry pi 3, running raspbian. 

Having the x86_64 script in the directory.
---------

strip:debian/test/usr/lib/games/test/test_Data/Plugins/x86_64/ScreenSelector.so: File format not recognized
dh_strip: strip --remove-section=.comment --remove-section=.note --strip-unneeded debian/test/usr/lib/games/test/test_Data/Plugins/x86_64/ScreenSelector.so returned exit code 1
debian/rules:43: recipe for target 'binary' failed
make: *** [binary] Error 29
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2

ls: cannot access '*.deb': No such file or directory


Having the x86 script in the directory.
---------

strip:debian/test/usr/lib/games/test/test_Data/Plugins/x86/ScreenSelector.so: File format not recognized
dh_strip: strip --remove-section=.comment --remove-section=.note --strip-unneeded debian/test/usr/lib/games/test/test_Data/Plugins/x86/ScreenSelector.so returned exit code 1
debian/rules:43: recipe for target 'binary' failed
make: *** [binary] Error 29
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2

ls: cannot access '*.deb': No such file or directory

**Comment by darealshinji** [comment]
> If it is any help I am also using a raspberry pi 3, running raspbian

That's the problem. It's using the default `strip` command which in case of Raspbian is made for arm architecture and apparently cannot handle binaries for x86_64 and i386. Luckily I have a Raspberry Pi too, so I can try to make it `cross-build` packages.

**Comment by darealshinji** [comment]
It's now possible to build packages on other systems than i386 or amd64. I can now build packages on Raspbian. However, binaries can't be stripped and dependencies cannot be tracked properly, so instead a list of typical Unity engine game dependencies are used. I definitely recommend you to build packages on i386 or amd64.

**Comment by chaosmasterro** [comment]
Just tried it, it works like a charm. Thank you! I will take that recommendation on using an i386 or amd64 as well.
