### ISSUE TITLE
Pointer turns invisible during X session.

### ISSUE THREAD

**Issue by chaosmasterro** [darealshinji/UnityEngine2deb#6]
Hello, I am unsure where to turn with this. When I start a game using an X session the pointer becomes invisible. When adjusting the settings you can tell the pointer is there by the highlights but it cannot be seen. 

Running a regular game from the desktop works fine, but it's only in X session.  I am swapping between the latest versions of debian and ubuntu.

**Comment by darealshinji** [comment]
Sounds like an issue with the game engine. `UnityEngine2deb` is only for packaging Unity games, so I don't think I can help. Try asking the developers of your game. If you have written the game yourself you might want to ask the Unity people.
